Mvp
SversusN/keeper pull request #1
Opened 2024-10-28 20:21 UTC by SversusN

2024-11-01 19:29 UTC, avhitrov requested changes
Практически все хорошо, кроме двух моментов:
- Не реализовано описанное в ТЗ поле Meta. Оно должно быть либо частью каждого типа (и попадать в зашифрованные данные) либо передаваться отдельно и не шифроваться (ТЗ это никак не реграментирует)
- Кеш реализован интересно, но, раз уж он реализован, то его периодически надо "перепрогревать": возможен еще один клиент от имени того же пользователя (например, компьютер + телефон), необходимо время от времени подтягивать свежие данные с сервера (например, начиная с какого нибудь ts).

В остальном нареканий нет. Реализация чистая.

2024-11-01 19:29 UTC, avhitrov commented on internal/client/models/models.go
> +type UserData struct {
По ТЗ:
```
Для любых данных должна быть возможность хранения произвольной текстовой метаинформации (принадлежность данных к веб-сайту, личности или банку, списки одноразовых кодов активации и прочее).
```

2024-11-01 20:00 UTC, SversusN commented on internal/client/models/models.go
> +type UserData struct {
Хм...у меня сама секретная информация в бинарном представлении. Я полагал, что наименование (UserData.Name) это и есть произвольная метаинформация по которой можно определить что внутри запрашиваемого. Хорошо.

2024-11-03 19:18 UTC, SversusN commented
Извините. =) Немного считерил добавил просто абстрактное поле в бинарные данные.

2024-11-03 19:18 UTC, SversusN commented on internal/client/models/models.go
> +type UserData struct {
+

2024-11-05 21:05 UTC, avhitrov approved these changes
Блестяще! Поздравляю с завершением дипломного проекта!

2024-11-06 18:11 UTC, merged